### PR TITLE
Cast object_pk to UUIDField when PK is a UUID

### PR DESCRIPTION
**Pull request by michael-k**
This a rebase of PR #675 and also includes a fix for databases without a native uuid field (all but PostgreSQL).  The fix was inspired by https://github.com/django/django/commit/d9881a025c15d87b2a7883ee50771117450ea90d.

Supersedes PR #675

### CODE REVIEW

**Comment by ad-m** [comment]
@michael-k , do you have a plan to create a new release? What do you need for that?

**Comment by michael-k** [comment]
No concrete plans.  We could do a 2.2.1 release since all commits except PR #686 are fixes or documentation updates.

If we do a 2.3.0 release, I'd like to drop support for Django 2.1 (EOL since December) as announces in the release notes of 2.2.0.  Even 1.11 LTS has now reached its EOL (on April 1st) and there's no reason to support anything < 2.2 LTS.
https://www.djangoproject.com/download

**Comment by lnagel** [comment]
Hey @michael-k - how could I help in getting a 2.2.1 release tagged?

The reason I'm asking is that I deployed an upgrade to Django 3.0 yesterday for a bigger project and we're stuck on 2.1.0 for the time being, but the admin views are not Django 3.0 compatible.

**Comment by ad-m** [comment]
@Inagel, first step for any release is update changelog. See for example #670 . When everything in CHANGELOG I see no obstacles to create even small release. See also #694, which would allow us to further increase the frequency of releases.

**Comment by lnagel** [comment]
I tried something, please see #695

**Comment by lnagel** [comment]
@michael-k Thanks for this PR - confirmed fixed for my Django 3.0 app as well!

**Pull request merged**
