### PR TITLE
Fixed GuardedModelAdminMixin views render for Django 1.10

### PR DESCRIPTION
**Pull request by tdruez**
#442

### CODE REVIEW

**Comment by brianmay** [comment]
Thanks for this. Probably should add Django 1.10 to the Travis tests at some stage too...

**Comment by tdruez** [comment]
Thanks for merging this, would you mind to issue a new release as well?
The current setup.py (non explicit version) makes it hard to use a non-tagged commit.
Thanks ++

**Comment by pombredanne** [comment]
I am facing the same issue. My head was spinning while trying to figure out how a simple setup.py versions was guessed .... Could there be a simpler, more explicit way that would be friendly to forks and temp dev releases? like using `version="1.4.5"` in `setup.py` .... eventually using `bumpversion` to propagate that in multiple places explicitky?

**Comment by AlexGrs** [comment]
Hi. 

Getting a release for this would be great for those having Django 1.10. 

Thank you.

**Comment by brianmay** [comment]
Version 1.4.5 has been released.

**Pull request merged**
