### PR TITLE
Add support for official Python/Django versions

### PR DESCRIPTION
**Pull request by irtazaakram**
Hi, 

This PR

* Add support for Django 4.1 & 4.2
* Add support for Python 3.10 & 3.11
* Drop support for Django 2.2, 3.0, 3.1 & 4.0
* Drop support for Python 3.5, 3.6 & 3.7

Please can we have a new release after this PR is merged.

Thanks,

### CODE REVIEW

**Comment by iamMHZ** [comment]
@irtazaakram 
Why should we drop support for Django 4.0?

**Comment by irtazaakram** [comment]
@iamMHZ 

Django 4.0 has reached its EOL https://www.djangoproject.com/download/#unsupported-versions

**Comment by johnthagen** [comment]
See also

- #816

**Comment by thclark** [comment]
We're about to get #816 merged so I'll close this, thanks so much for your work folks!

**Pull request closed without merging**
