### PR TITLE
Bulk assign permissions for multiple objects

### PR DESCRIPTION
**Pull request by ad-m**
Hello,

I updated code from #432 made by @phinjensen to:
- consolidate UserObjectPermissionManager and GroupObjectPermissionManager,
- add efficient implementation of ```assign_perm``` and ```remove_perm``` for bulk action,
- accept ```Permission``` instance as argument for ```assign_perm``` and ```remove_perm```` (Due some working idea on implementations bulk_assign_perm and leave these good changes.).

Greetings,

### CODE REVIEW

**Comment by brianmay** [comment]
So does this mean we can now close #432 and use this one instead?

**Comment by ad-m** [comment]
@brianmay , yes. I made second pull requests to made changes without anyone's help.

**Comment by brianmay** [comment]
Do you consider this ready for merging?

**Comment by ad-m** [comment]
Yes.

Wysłano z urządzenia mobilnego.

4 lip 2016 10:36 AM "Brian May" <notifications@github.com> napisał(a):

**Pull request merged**
