### PR TITLE
Optimize get_objects_for_* if klass is a queryset

### PR DESCRIPTION
**Pull request by TauPan**
This fixes our use-case regarding https://github.com/django-guardian/django-guardian/issues/189.

In particular the generated query for a benchmark test with 900 possible candidates now only contains the one relevant id (as opposed to all 900) and yields a performance increase of a factor of 100.

Please have a look and tell me what you think!

(I'm also wondering if you would be opposed to some more refactorings as it's obvious that `get_objects_for_user`  and `get_objects_for_group` are very similar and have large stretches of identical code.)

### CODE REVIEW

**Comment by TauPan** [comment]
I've updated this to 2.2.0 just now. Please notify me if there's anything I can do to help get this merged at some point.

**Comment by ad-m** [comment]
In the case of this issue, I would like to wait for issue # 675, because it fixes the current functionality and brings additional tests, in the area in which this code - in my opinion - may potentially require attention.

**Comment by danaspiegel** [comment]
now that #675 is closed (superseded by #691), can we get this merged in? We're seeing significant slowdowns on views where this is an issue.

**Comment by bellini666** [comment]
Hey guys. Is this ever going to be merged?

**Comment by ad-m** [comment]
For me ok to merge. I would like merge that as soon as rebased.

@TauPan could you rebase?

**Comment by TauPan** [comment]
> For me ok to merge. I would like merge that as soon as rebased.
> 
> @TauPan could you rebase?

Done. github tells me that travis needs maintainer approval.

**Comment by ad-m** [comment]
Approved on CI.

**Comment by TauPan** [comment]
Sorry, my patch to silence the pytest collection warnings made the tests fail. I've removed that (and actually ran tox locally this time) sorry.

**Comment by ad-m** [comment]
Don't worry. Approved on CI again.

**Comment by bellini666** [comment]
Hey guys, thanks for merging this :)
Just to know, are there any ETA on the next release of django-guardian?

**Comment by ad-m** [comment]
>  Just to know, are there any ETA on the next release of django-guardian?

No

**Comment by sevdog** [comment]
For completeness I am using the change to this PR which is like [this commit](https://github.com/kmmbvnr/django-guardian-ng/commit/83c34f7d13e29259e7f59cec2a7f3e23b4045c1b). The point is still the same: this change just adds a redundanct query to the model table which is going to fetch everything inside that for no real reason.

**Comment by TauPan** [comment]
The actual performance might depend on the indices on your database. I'm not actively using django-guardian any more, so others might have a more current insight into the django-guardian codebase at this point. I'll see myself out.

**Pull request merged**
