### PR TITLE
Django 1.8 compatibility

### PR DESCRIPTION
**Pull request by clarkperkins**
This hasn't been tested on django < 1.6, but it definitely works on django 1.8.

### CODE REVIEW

**Comment by clarkperkins** [comment]
I know the travis build info isn't showing here, but this successfully passed all tests in travis.

**Comment by cabello** [comment]
I've checked out your fork & branch and I was able to visit "Object Permissions" in admin. I am not the project maintainer but :+1: !

**Comment by failedguidedog** [comment]
+1

**Comment by ericholscher** [comment]
Would be great this merged. Currently running off this branch because master breaks on 1.8.

**Comment by cabello** [comment]
@lukaszb Can you take a second look on this one please?

**Comment by lukaszb** [comment]
Run tests at https://travis-ci.org/django-guardian/django-guardian/builds/83927071

**Comment by Seraf** [comment]
Hello, 
is it possible to do a pypi release with these patches please ?

**Comment by lukaszb** [comment]
@Seraf  done

**Comment by Seraf** [comment]
@lukaszb thanks for your reactivity !!

**Pull request merged**
