### PR TITLE
Fixed minimum Django version number.

### PR DESCRIPTION
**Pull request by roskakori**
There seems to be typo in the version number, Django 1.2 would be ancient.

### CODE REVIEW

**Comment by michael-k** [comment]
It's not a typo, it's just very old and hasn't been touched in 3 years.  I think the whole paragraph should be adjusted.

**Comment by roskakori** [comment]
> It's not a typo, it's just very old and hasn't been touched in 3 years. I think the whole paragraph should be adjusted.

Hm, then it's a bit confusing in combination with the following sentence in `installation.rst`:

> This application requires Django 2.2 or higher

So what the docs try to say is that django-guardian requires Django 2.2+, while some other libraries require a Django version before 1.2, which might be a major selling point to some people?

**Comment by ad-m** [comment]
This sentence has not been updated in years. It requires a general review to see if it still provides relevant information. I think the reference to 1.2+ is no longer relevant to anybody. We can remove this sentence. Perhaps, however, it is worth considering changing the entire paragraph, because alternative libraries have also appeared.

**Comment by michael-k** [comment]
I propose to close this due to inactivity.

**Pull request closed without merging**
