### PR TITLE
Fix Django 1.8 tests

### LINKED ISSUE #358: confusion with permission tables django 1.8
There seems to be confusion with UserObjectPermission defined in guardian.models and ProjectUserObjectPermission defined in guardian.testapp.models at least under Django 1.8.

The guardian functions use UserObjectPermission however the test functions use ProjectUserObjectPermission.

I am guessing that Guardian is suppose to use ProjectUserObjectPermission too, however I can't see where this redirection is suppose to take place.

### PR DESCRIPTION
**Pull request by brianmay**
Closes #358.

For me this results in all tests passing under Django 1.8.

Lets see if the CI agrees with me...

### CODE REVIEW

**Comment by brianmay** [comment]
All tests pass. Probably should add Python3.5/Django 1.8 to Travis-CI too. Not sure if Travis-CI picks that up automatically from tox.ini or if it needs to be configured.

**Comment by lukaszb** [comment]
Needs to be configured at .travis.yaml, actually. Would you do that in this PR?

**Comment by brianmay** [comment]
Had a look, not sure I understand the syntax properly. We need to make sure that Python3.5 tests only run for Django 1.8. I probably should make an effort to learn about travis sometime.

Would this be sufficient, or would it try to run Python3.5 tests with Django1.7?

```diff
diff --git a/.travis.yml b/.travis.yml
index b7b81be..b27ba63 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,6 +5,7 @@ python:
  - 2.7
  - 3.3
  - 3.4
+ - 3.5
 
 env:
  - DJANGO_VERSION=1.2.7
```

**Comment by ad-m** [comment]
@brianmay , you can do it in this way. If you append python version you will tests over all django version, django 1.7 over python 3.5 too. You can fg. exclude by blacklist:
```yml
matrix:
    exclude:
        - python: 3.5
          env: DJANGO_VERSION=1.7
```
You can use whitelist too fg:
```yml
env:
  global:
    - DATABASE_URL="mysql://root:@localhost/test_feder"
    - DJANGO_SETTINGS_MODULE="config.settings.travis"
  matrix:
    - TOX_ENV=py27-dj18
    - TOX_ENV=py33-dj18
    - TOX_ENV=py27-djmaster
    - TOX_ENV=pypy-dj18
    - TOX_ENV=pypy-djmaster
    - TOX_ENV=flake8
```
If you use whitelist you can use allow_failures list too:
```yml
matrix:
  allow_failures:
    - env: TOX_ENV=flake8
    - env: TOX_ENV=py33-dj18
    - env: TOX_ENV=py27-djmaster
    - env: TOX_ENV=pypy-dj18
    - env: TOX_ENV=pypy-djmaster
```

**Comment by brianmay** [comment]
Tests fixed up. I used the blacklist method, because it is already used. I also updated some files to clarify that Python 2.6 is not supported anymore - the tests failed for every Django version. Have a vague recollection that recent Django versions do not support Python 2.6 anyway. I also enabled the Django 1.7.x tests which were (possibly accidentally) disabled.

**Comment by lukaszb** [comment]
Thank you so much!

**Pull request merged**
