### PR TITLE
Fix failing checks

### PR DESCRIPTION
**Pull request by BonaFideIT**
In order to get guardian back on track and keep it active, we consider it essential that the github actions run properly.

Currently, all tests on the devel branch are failing, as described in https://github.com/django-guardian/django-guardian/issues/818.

With this PR we revert the changes of the last 2 merged PRs, because before these all tests pass, #812 and #768. We should also set up a policy that tests cannot be merged if they fail.

In addition, we introduce minimal changes in this PR that make all checks green again.

We also suggest to investigate #812 and #768 again to see why the problem with the checks occurred. We should re-open the issues.

### CODE REVIEW

**Comment by BonaFideIT** [comment]
Please review this PR: @brianmay, @johnthagen, @thclark, @cmaggiulli.

**Review by thclark — APPROVED** [review]

**Comment by thclark** [comment]
@cmaggiulli can you review this please? Along with lots of others I'm quite keen to see the library resurrect!

**Review by brianmay — APPROVED** [review]

**Comment by thclark** [comment]
OK, we're into `devel` (which for some reason is actually the main branch). Thank you so much @BonaFideIT! I'll start fighting to get this released to pypi as it doesn't seem to be automated.

**Comment by BonaFideIT** [comment]
@thclark can we maybe get a new RC package for the current devel branch? We would like to deploy the fixes from our merge requests. We have a CI running our project tests with devel which passes all tests - so we are carefully confident the changes in this new version are solid.

A RC package would allow us uncomplicated deployment without pinning any commits and allow new users to work the the LTS from 2021 until we get the 3.0 release.

thanks! BF.IT

**Pull request merged**
