### PR TITLE
Add chinese translation.

### PR DESCRIPTION
**Pull request by lintingbin2009**
Add chinese translation.

### CODE REVIEW

**Comment by ad-m** [comment]
@Jay54520 (author #578), could you review that pull request?

**Comment by Jay54520** [comment]
@ad-m Ok, I'll review now.

**Comment by Jay54520** [comment]
@lintingbin2009 How do you generate the `django.po`, there are some missing such as 

```
#: guardian/admin.py:462
msgid "Enter a value compatible with User.USERNAME_FIELD"
```

And I think this PR is duplicate with https://github.com/django-guardian/django-guardian/pull/578/files.

**Comment by lintingbin2009** [comment]
> @lintingbin2009 How do you generate the `django.po`, there are some missing such as
> 
> ```
> #: guardian/admin.py:462
> msgid "Enter a value compatible with User.USERNAME_FIELD"
> ```
> And I think this PR is duplicate with https://github.com/django-guardian/django-guardian/pull/578/files.

Not, I copy "django.po" from the other language.

**Pull request closed without merging**
