### PR TITLE
Improving tests in testapp using manage.py

### PR DESCRIPTION
**Pull request by Wtower**
Improve tests using a `manage.py`.
Relevant issue #364

### CODE REVIEW

**Comment by brianmay** [comment]
Doesn't seem to work for me without the following change:

```
diff --git a/guardian/testapp/manage.py b/guardian/testapp/manage.py
index bcdef77..2a10a60 100755
--- a/guardian/testapp/manage.py
+++ b/guardian/testapp/manage.py
@@ -6,7 +6,7 @@ if __name__ == "__main__":
     # should be ../../ (`djangoguardian/`)
     BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
 
-    sys.path.append(BASE_DIR)
+    sys.path.insert(0, BASE_DIR)
 
     os.environ.setdefault("DJANGO_SETTINGS_MODULE", "guardian.testapp.testsettings")
```

On my system, `guardian/testapp` is getting inserted at the start of the sys.path, and it looks like this new entry has to appear first.

**Comment by brianmay** [comment]
Was also confused with the title of this pull request: has nothing to do with `example_project`, but `guardian/testapp`.

**Comment by Wtower** [comment]
Ok, I will take a look at that, not today though, rough day. You are right on the title, I just used the issue title but it's completely irrelevant.

**Comment by Wtower** [comment]
I'm back. I was wondering, are you not using a virtualenv? There is for example a [specific question in SO](http://stackoverflow.com/questions/10095037/why-use-sys-path-appendpath-instead-of-sys-path-insert1-path) that recommends use append vs insert, and that this error can be dealt with virtualenv.

Changing the code as you recommended makes no difference to me btw, still running ok so I don't really mind. I was just wondering if this is the correct approach.

Also edited the title.

**Comment by Wtower** [comment]
Also to mention that tests fail for Django 1.7.0, require >=1.7.1 due to 

    TypeError: __init__() got an unexpected keyword argument 'preserve_default'

Which has been dealt in 1.7.1. See [relevant link](http://stackoverflow.com/questions/26432242/django-1-7-migrations).

**Comment by brianmay** [comment]
Made some minor changes and merged this as 6359074a9cbe997cea06a478b19911a15a663795.

Looking at `tests.py` - I see it makes to the settings, which perhaps should get merged into `testsettings.py`.

Not sure there is any need for `tests.py` anymore actually, the `manage.py` looks like a better solution.

**Comment by Wtower** [comment]
Yes, I agree with that. Reduce complexity.

**Pull request closed without merging**
