### PR TITLE
fix autofield in django3.2

### PR DESCRIPTION
**Pull request by RainshawGao**

### CODE REVIEW

**Comment by johnthagen** [comment]
I presume this is to fix the following warnings when run in Django 3.2:

```
WARNINGS:
guardian.GroupObjectPermission: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the GuardianConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
guardian.UserObjectPermission: (models.W042) Auto-created primary key used when not defining a primary key type, by 
```

**Comment by thclark** [comment]
Yep, this also prevents a new migration being created when running `python manage.py makemigrations` with django 3.2.

Looks good to go to me...

**Comment by ad-m** [comment]
Thank you all for review! Merged based on positive community reviews.

I am not actively developing Django projects and I do not follow its development.

**Comment by johnthagen** [comment]
@ad-m Thanks. Do you have permissions to release to PyPI?

Also, given `django-guardian`'s important state in the Django ecosystem, have you considered having the project join jazzband? https://jazzband.co/

**Comment by ad-m** [comment]
@johnthagen I have permission to PyPI. I have plan to make a new release in weekend.

**Pull request merged**
