### PR TITLE
"Fix" performance enhancement related to #811

### PR DESCRIPTION
**Pull request by cmaggiulli**
Please see [Git Issue 811](https://github.com/django-guardian/django-guardian/issues/811) for a description of the problem

### CODE REVIEW

**Comment by thclark** [comment]
@cmaggiulli please could you check we have test coverage for this line? My whole thing is: "LGTM but why was the `list()` there in the first place?!"

**Review by thclark — APPROVED** [review]

**Comment by thclark** [comment]
@ad-m or @brianmay if you wouldn't mind reviewing this; @cmaggiulli is my triage-and-merge partner and he'll be unable to review his own PR!

**Comment by brianmay** [comment]
I would imagine that it was done this way either due to misunderstanding of what was possible or due to some legacy issue with the Django ORM.

**Review by brianmay — APPROVED** [review]

**Comment by cmaggiulli** [comment]
> My whole thing is: "LGTM but why was the `list()` added in the first place?!"

Yes will certainly add!

**Comment by cmaggiulli** [comment]
This is breaking all the test cases.  I have the fix I will be merging before Sunday

**Pull request merged**
