### PR TITLE
Allow content type retrieval to be overridden.

### PR DESCRIPTION
**Pull request by benkonrath**
This is an implementation of user settable content type retrieval that I mentioned in  #421. I'd like to hear your thoughts on this strategy. This is just a first version. I still need to complete a few tasks but I wanted to make sure I'm heading in the right direction before I finish this up. Let me know what you think.

Here are the outstanding tasks:
* Add tests
* Add docs
* Remove `get_polymorphic_base_content_type` method as it should be in my project or django-polymorphic.

### CODE REVIEW

**Comment by brianmay** [comment]
Just wondering if there are any applications other then django-polymorphic for overriding the content type.

I guess the point of this change is to remove the django-polymorphic specific code from django-guardian however still allow django-guardian to be customized to support django-polymorphic. Which seems like a good idea to me.

**Comment by benkonrath** [comment]
Thanks for your feedback. The idea to separate out the code comes from @lukaszb's comment on #338:

> As to the second issue, regarding django-polymorphic - as a rule of thumb we are not supporting 3rd party packages that does something with your model, sorry. If someone would want to work on it, feel free to create another package that would bind guardian and polymorphic.

I'll move forward with this PR and close #421. I don't know if there are any other projects that would need to override the content type but I still think it's a good idea to have this code in the django-polymorphic project or in a 3rd-party module.

**Comment by benkonrath** [comment]
Ok, I've added the docs, added a test and removed the django-polymorphic code. I'm planning to make a pull request to django-polymorphic with the removed function once this is merged.

Let me know if you have any suggestions on how to improve the docs, tests and the code in general. Thanks.

**Comment by benkonrath** [comment]
I can rebase and squash this PR into one commit when it's ready to be merged.

**Comment by brianmay** [comment]
Is this ready for merging? @ad-m what do you think?

**Comment by benkonrath** [comment]
It's ready by my account. I'm already using it. Any feedback is appreciated.

**Comment by benkonrath** [comment]
I just rebased this PR for the latest changes. Let me know if there's anything more I can do to help get this PR merged. Thanks.

**Comment by brianmay** [comment]
I was hoping to get @ad-m's opinion before merging.

@benkonrath What do you think however? Is this ready for merging?

**Comment by ad-m** [comment]
LGTM.

**Comment by benkonrath** [comment]
@brianmay I think it's ready but I'd still like to have it reviewed so that I can fix issues with style, documentation, etc. Thanks.

**Comment by ad-m** [comment]
@benkonrath , so as maintainer I am waiting to that fixes before merging. Ping me when done, please.

**Comment by benkonrath** [comment]
@ad-m I've just rebased this PR and it's ready to be merged.

**Comment by ad-m** [comment]
Thank you for your contribution.

tumblr_lnmamsqqng1qlh1s6o1_500

**Pull request merged**
