### PR TITLE
Drop support for Django < 1.11

### PR DESCRIPTION
**Pull request by michael-k**
I tried to make small commits for easier reviews and exclusions of commits.  Feel free to squash them when merging the PR.

According to `Supported Versions` in https://www.djangoproject.com/download/, support for
- Django 1.9 ended in April 2017,
- Django 1.10 ended in December 2017,
- Django 1.8 ended at April 1, 2018.

The django maintainers suggested to drop support for Django < 1.11 in third party libraries with the release of Django 2.0 at December 2, 2017.  See https://docs.djangoproject.com/en/2.0/releases/2.0/#third-party-library-support-for-older-version-of-django

### CODE REVIEW

**Comment by michael-k** [comment]
Can someone merge this?  I'd like to add official Django 2.1 support, but not before support for Django < 1.11 was dropped.

**Comment by michael-k** [comment]
@ad-m You already reviewed most of the changes.  Can you give the remaining 4 commits a review and pull them in?  They are fairly small, should be easy to review and do not touch the core implementation.

**Comment by ad-m** [comment]
@michael-k , thank for you work. I will release new version of django-guardian at end of the week.

**Comment by jmsmkn** [comment]
@ad-m Do you know when you'll make the new release? I maintain a project that depends on django-guardian and would like to add Django 2.1 support too. Thanks!

**Pull request merged**
