### PR TITLE
Add database index to object_pk field in BaseGenericObjectPermission

### PR DESCRIPTION
**Pull request by dblenkus**
`object_pk` field is used for filtering (eg [here](https://github.com/django-guardian/django-guardian/blob/ab4e14e76c9228a7f6e256399799e1439c441b85/guardian/shortcuts.py#L275), [here](https://github.com/django-guardian/django-guardian/blob/ab4e14e76c9228a7f6e256399799e1439c441b85/guardian/shortcuts.py#L291) and [here](https://github.com/django-guardian/django-guardian/blob/ab4e14e76c9228a7f6e256399799e1439c441b85/guardian/shortcuts.py#L367)), so a database index can significantly speeds up those queries, especially on big production databases.

### CODE REVIEW

**Comment by ad-m** [comment]
Why not combined index (```index_together```) on ```object_id``` and ```content_type```?

**Comment by dblenkus** [comment]
Good point! I've updated the pull request.

**Comment by ad-m** [comment]
Currently a supported version of Django is 2.1+. Since 1.11 ```index_together``` is deprecated, use ```indexes``` instead to avoid introducing technical debt. See Django docs https://docs.djangoproject.com/en/2.2/ref/models/options/#index-together also.

**Comment by dblenkus** [comment]
Thanks for pointing this out. Fixed.

**Comment by ad-m** [comment]
Thank you for your cooperation and project development.

**Pull request merged**
