### PR TITLE
bulk_remove_perm removes all permissions without using the queryset

### PR DESCRIPTION
**Pull request by fgaudin**

### CODE REVIEW

**Comment by fgaudin** [comment]
breaking tests on python2.7 with postgres

**Comment by ad-m** [comment]
@fgaudin , do you think it is a ready?

**Comment by fgaudin** [comment]
it is

**Comment by ad-m** [comment]
@brianmay , do you can rebase and merge it?

**Comment by ad-m** [comment]
Thank you for contributions.

**Pull request merged**
