### PR TITLE
Add docs and update tests for PermissionListMixin

### PR DESCRIPTION
**Pull request by ad-m**
Hello, 

In #434 I suggested add ```PermissionListMixin```. I expected review and comments before write docs, but pull requests was merged without that. In next django-guardian release I want add ```PermissionListMixin``` with full support, so it's good to add docs and tests.

I expect english and docs syntax review. I don't know English the best and I don't write docs a lot. ```PermissionListMixin.get_required_permissions``` break DRY principle due ```PermissionRequredMixin.get_required_permissions```, but I don't know how to write them to make docs still clear.

I hope for @brianmay  support.

Greetings,

### CODE REVIEW

**Comment by ad-m** [comment]
@brianmay , here is CHANGES after merge above commit:
```
- Improve performance of get_objects_for_user
- Add test-covered and documented guardian.mixins.PermissionListMixin
- Allow content type retrieval to be overridden fg. for django-polymorphic support
- PermissionRequiredMixin support CreateView-like (no object) view
- Add django 1.10 to TravisCI and tox
- Run tests for example_project in TravisCI
- Require django 1.9+ for example_project (django-guardian core support django 1.7+ still)
- Fix django versions compatibility in example_project
```
I skip no-feature changes like drop some warning in docs build etc. It need grammar checks too, so I don't put in repo.

**Comment by brianmay** [comment]
Looks good to me. It really doesn't need to be perfect grammar wise, just as long as see what has been changed in each version at a glance.

The obsessed work colleague of mine would complain that the sentences don't end with a full stop.

Can you please add this to CHANGES and commit? Thanks.

**Comment by ad-m** [comment]
@brianmay , well done. CHANGES updated. I am not sure how prepare pypi packages with setuptools_scm etc.

**Comment by brianmay** [comment]
I can do that, probably tomorrow now. I can also list the steps I use if you want too.

**Comment by ad-m** [comment]
I don't have permission and I like review, so I leave doing releases for you.

**Comment by brianmay** [comment]
Done.

**Pull request merged**
