### PR TITLE
Drop support for Django 2.1

### PR DESCRIPTION
**Pull request by michael-k**
Reached its EOL on 2019-12-02
https://www.djangoproject.com/download/#supported-versions

Should be included in 2.3.0, but not in 2.2.x. See https://django-guardian.readthedocs.io/en/stable/develop/changes.html#release-2-2-0-january-3-2020

### CODE REVIEW

**Comment by lnagel** [comment]
@ad-m @michael-k What is the current situation with this PR? Is there any remaining work to be done or can it be merged so 2.3.0 could be released?

**Comment by ad-m** [comment]
It requires reviewing, assessing whether something has not been overlooked, e.g. through comments from the community. At GitHub, anyone can review and accept changes. This PR has not gained any acceptance from anybody so far.

Do you see any remaining work to be done?

**Comment by lnagel** [comment]
I have read through the code and checked that the builds pass. The contents of the PR are rather straightforward to me personally, so in my eyes there is no remaining work to be done here.

**Comment by lnagel** [comment]
Django 2.2 supports Python 3.5, 3.6, 3.7, and 3.8 - so in my eyes also the test versions matrix is accurately set up.

**Comment by ad-m** [comment]
Thank you for your opinion. Any comments of this kind help to ensure that the proposed change is correct and should be merged. If you feel like it - you can also help and review other PRs in this project, which often require a bit of support to improve their quality to an acceptable level. The project is based on community work and community communication is essential for its development.

**Comment by michael-k** [comment]
No objection in 3 weeks; since the next release we're doing is 2.3, I'm merging this

**Pull request merged**
